// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcNWE1HFqfLMbOX7U5ge5aptXVv5Hr7c',
    appId: '1:326562547668:web:0b1e17bb3aecd6d1d67841',
    messagingSenderId: '326562547668',
    projectId: 'fir-flutter-codelab-6fde9',
    authDomain: 'fir-flutter-codelab-6fde9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-6fde9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeKXomS74E5bAh4MoUniHGCkHcqImL27c',
    appId: '1:326562547668:android:fa5a2cb167ff2321d67841',
    messagingSenderId: '326562547668',
    projectId: 'fir-flutter-codelab-6fde9',
    storageBucket: 'fir-flutter-codelab-6fde9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_ElQwxdfHf8RrNT5404dT-BSO-AEVxM',
    appId: '1:326562547668:ios:6099c11827dac648d67841',
    messagingSenderId: '326562547668',
    projectId: 'fir-flutter-codelab-6fde9',
    storageBucket: 'fir-flutter-codelab-6fde9.appspot.com',
    iosClientId: '326562547668-1josl7ugi842ka1pvvfie9l8887gtcb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_ElQwxdfHf8RrNT5404dT-BSO-AEVxM',
    appId: '1:326562547668:ios:6099c11827dac648d67841',
    messagingSenderId: '326562547668',
    projectId: 'fir-flutter-codelab-6fde9',
    storageBucket: 'fir-flutter-codelab-6fde9.appspot.com',
    iosClientId: '326562547668-1josl7ugi842ka1pvvfie9l8887gtcb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
